### ISSUE TITLE
Request for Kibana 6.x

### ISSUE THREAD

**Issue by tatdatpham** [sw-jung/kibana_markdown_doc_view#1]
Thank for amazing plugin. do you have plan to update for kibana 6.x plugin?

**Comment by sw-jung** [comment]
I'm sorry for delaying update, and I planning it to end of this year!

I want to do it as soon as possible, but I don't have available time now. 😭

**Comment by sw-jung** [comment]
@tatdatpham

Release ~v6.1.1 has been completed.

Happy New Year! 🎊
