### ISSUE TITLE
Could not locate that index-pattern

### ISSUE THREAD

**Issue by karnamonkster** [sw-jung/kibana_markdown_doc_view#2]
Hi,
I am trying to create the markdown template but getting the error
Could not locate that index-pattern (id: {{indexPattern.id}}), click here to re-create it

**Comment by sw-jung** [comment]
Could you answer the following questions?

1. What's your kibana version?
2. Have you ever upgraded from kibana 5.x to 6.x? If you upgraded, which version did you upgrade from~to?
3. What page was the error? Can I see the capture of that error page?

**Comment by karnamonkster** [comment]
What's your kibana version? 5.6.2
    Have you ever upgraded from kibana 5.x to 6.x? If you upgraded, which version did you upgrade from~to? No
    What page was the error? Can I see the capture of that error page?
The error comes when from the Discover Tab i click on the 
`Looks like you don’t have markdown template for this index pattern. Let's create it! `
Once i click on "Create Markdown Template"

**Comment by karnamonkster** [comment]
[Error 1 snapshot](https://gist.github.com/karnamonkster/b897b89b7e0f1d2f51b2e5d28f066905 )

After when i select an index pattern and try to create the markdown
[Error 2 snapshot](https://gist.github.com/karnamonkster/b897b89b7e0f1d2f51b2e5d28f066905#file-markdown2-png)

**Comment by sw-jung** [comment]
Thank you for your answer.

The "Create Markdown Template" button on the Discover page seems to have an error, but the button is linked to the Management - Markdown Templates - [IndexPattern what you want to setting template] page. Please use this page before resolving.

I'll try to resolve it ASAP! 😄

**Comment by sw-jung** [comment]
> [Error 1 snapshot](https://gist.github.com/karnamonkster/b897b89b7e0f1d2f51b2e5d28f066905 )

I found it's already resolved in 042a06620e0379fda2e191f64df861ceff459a01. I'll patch missing backports. 😄

> After when i select an index pattern and try to create the markdown
> [Error 2 snapshot](https://gist.github.com/karnamonkster/b897b89b7e0f1d2f51b2e5d28f066905#file-markdown2-png)

It seems to attempting automatic type creation failed.(like [this](https://github.com/elastic/elasticsearch/issues/22740)) but I can't replay it.
This plugin doesn't do automatic type creation in normal situation.

I tested 2 cases below:
1. Install kibana -> Install markdown_doc_view -> Run kibana -> Create template
2. Install kibana -> Run kibana and stop -> Install markdown_doc_view -> Run kibana -> Create template

Can I have more information? I'm very interested in this issue!
- `kibana.yml`
- Kibana index settings&mappings: `GET .kibana-6`
- Any templates to participate in creating your kibana index: `GET _template`
- Installation step of kibana&markdown_doc_view

**Comment by karnamonkster** [comment]
Here is the [kibana.yml](https://gist.github.com/karnamonkster/14febad86debb3decaa91e488ece735c) 
[Kibana Index settings & Mapping:](https://gist.github.com/karnamonkster/6a0b8284e94c29616f83b21987b4ce09#file-kibana-index)
No templates
Installation step :
`bin/kibana-plugin install file:///pathtothefile.zip`

`Restarted kibana`

**Comment by sw-jung** [comment]
Your kibana index mappings looks elasticsearch 6.x style, but this plugin support it from v6.x.

I've released a patch for this issue. Please check it! -> [v5.6.2-patch1](https://github.com/sw-jung/kibana_markdown_doc_view/releases/tag/v5.6.2-patch1)
