### ISSUE TITLE
How to change a markdown template?

### ISSUE THREAD

**Issue by karnamonkster** [sw-jung/kibana_markdown_doc_view#3]
I created a markdown template for one of the index patterns, but now i need to update the same.
Could you please guide me from where to do the same

**Comment by karnamonkster** [comment]
Sorry about the issue, fixed it

**Comment by aup8497** [comment]
I'm still not able to find how to change the template :(

**Comment by sw-jung** [comment]
@aup8497 You can change it in `management/kibana/markdown-template`.
