### ISSUE TITLE
Kibana 6.2.4

### ISSUE THREAD

**Issue by pedrotcm** [sw-jung/kibana_markdown_doc_view#4]
After changed package.json to version 6.2.4 and tryed install, i got the error below.

![image](https://user-images.githubusercontent.com/5384202/40062468-adce2ed2-5831-11e8-8719-1e9765284b9e.png)

**Comment by pedrotcm** [comment]
After downloaded the release 6.2.3, i deleted the optimized folder and tried again, the installation was completed with success.

**Comment by sw-jung** [comment]
6.2.4 Release added [here](https://github.com/sw-jung/kibana_markdown_doc_view/releases/tag/v6.2.4). Thank you for your interest.
